#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int TURN_DEGREES = 147;
const int LOOK_LENGTH = 30;

bool isNearWall() {
	return SensorValue[sonar] < 15;
}

bool isOverLine() {
	return SensorValue[light] < 60;
}

void leftTurn() {
	turnLeft(TURN_DEGREES, degrees, 100);
}

void rightTurn() {
	turnRight(TURN_DEGREES, degrees, 100);
}

void creepForward() {
	forward(45, degrees, 100);
}

void recenter() {
	int checkDistance = 15;
	float currentDistance = SensorValue[sonar];
	turnRight(checkDistance, degrees, 100);
	if (currentDistance > SensorValue[sonar]) {
		turnLeft(checkDistance * 2, degrees, 100);
		if (currentDistance > SensorValue[sonar]) {
			turnRight(checkDistance, degrees, 100);
		}
	}
}

void creepToLine() {
	while (!isOverLine()) {
		creepForward();
	}
	forward();
}

bool isPathOpen() {
	recenter();
	if (SensorValue[sonar] > LOOK_LENGTH) {
		return true;
	}
	return false;
}

bool isRightOpen() {
	bool isOpen;
	rightTurn();
	isOpen = isPathOpen();
	leftTurn();
	return isOpen;
}

bool isLeftOpen() {
	bool isOpen;
	leftTurn();
	isOpen = isPathOpen();
	rightTurn();
	return isOpen;
}

bool turnLeftIfOpen() {
	if (isLeftOpen()) {
		leftTurn();
		return true;
	}
	return false;
}

bool turnRightIfOpen() {
	if (isRightOpen())	{
		rightTurn();
		return true;
	}
	return false;
}

void forwardUntilWall() {
	while(isPathOpen()) {
		forward(2);
	}
}

void turnRight90(){

	int rightAngle = 147;
	turnRight(rightAngle, degrees, 100);
}

int getTurnWithLongestDistance(float *distances) {

	int turnWithLongestDistance = 1;
	float currentDistance = distances[0];

	int length = sizeof(distances);

	for (int i = 1; i < length ; i = i + 1) {
		if (distances[i] > currentDistance) {
			currentDistance = distances[i];
			turnWithLongestDistance = i + turnWithLongestDistance;
		}
	}

	return turnWithLongestDistance;
}

void startVehicleAndSetDirection() {
	float distance[4];

	for ( int i = 0; i < 4; i = i + 1) {
		turnRight90();
		distance[i] = SensorValue[S4];
	}

	int longestTurn = getTurnWithLongestDistance(distance);

	for (int y = 0; y < longestTurn; y = y + 1){
		turnRight90();
	}
}

task main()
{
	startVehicleAndSetDirection();
	forwardUntilWall();
	leftTurn();
	forwardUntilWall();
	leftTurn();
	while (!isRightOpen()) {
		creepToLine();
	}
	rightTurn();
	forwardUntilWall();
	rightTurn();
	creepToLine();
	rightTurn();
	creepToLine();
	leftTurn();
	creepToLine();
	leftTurn();
	forward(10);
}
